global using Microsoft.EntityFrameworkCore;
global using Ordering.Domain.Models;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Ordering.Domain.ValueObjects;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Ordering.Domain.Enums;
global using Ordering.Infrastructure.Data;
global using System.Reflection;