// <auto-generated />
using System;
using CashingWithPaginationDemo.Src;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashingWithPaginationDemo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("CashingWithPaginationDemo.Src.EntityModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Counter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value6")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value7")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value8")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EntityModels");
                });
#pragma warning restore 612, 618
        }
    }
}
